default_config: default
configs:
    default:
        contentsCss: '/build/app.css'
        height: 450
        allowedContent: true
        format_tags: 'p;h2;h3;h4;h5;h6;pre;address;div'
        fontSize_sizes: '1/1.125rem;2/1.25rem;3/1.375rem;4/1.5rem;5/1.625rem;6/1.75rem;7/1.875rem;8/2rem'

        toolbarGroups:
            - { name: 'document', groups: [ 'mode', 'tools', 'document', 'doctools' ] }
            - { name: 'clipboard', groups: [ 'clipboard', 'cleanup', 'undo' ] }
            - { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] }
            - '/'
            - { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] }
            - { name: 'links', groups: [ 'links' ] }
            - { name: 'insert', groups: [ 'insert' ] }
            - '/'
            - { name: 'basicstyles', groups: [ 'basicstyles' ] }
            - { name: 'styles', groups: [ 'styles' ] }
            - { name: 'colors', groups: [ 'colors' ] }
            - { name: 'others', groups: [ 'others' ] }
            - { name: 'about', groups: [ 'about' ] }

        removeButtons: 'BidiLtr,BidiRtl,Language,Scayt,Flash,Smiley,Iframe'
        extraPlugins: 'inserthtml,imagesgallery'
        templates: 'images_gallery'
        templates_replaceContent: false

plugins:
    inserthtml:
        path:     '/bundles/hitckitcore/ckeditor/insert-html/'
        filename: 'plugin.js'

    imagesgallery:
        path:     '/bundles/hitckitcore/ckeditor/images-gallery/'
        filename: 'plugin.js'
