default_config: default
configs:
    default:
        contentsCss: '/build/ckeditor.css'
        height: 350
        allowedContent: true
        format_tags: 'p;h2;h3;h4;h5;h6;pre;address;div'

        toolbarGroups:
            - { name: 'document', groups: [ 'mode', 'tools', 'document', 'doctools' ] }
            - { name: 'clipboard', groups: [ 'clipboard', 'cleanup', 'undo' ] }
            - { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] }
            - '/'
            - { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] }
            - { name: 'links', groups: [ 'links' ] }
            - { name: 'insert', groups: [ 'insert' ] }
            - '/'
            - { name: 'basicstyles', groups: [ 'basicstyles' ] }
            - { name: 'styles', groups: [ 'styles' ] }
            - { name: 'colors', groups: [ 'colors' ] }
            - { name: 'others', groups: [ 'others' ] }
            - { name: 'about', groups: [ 'about' ] }

        removeButtons: 'BidiLtr,BidiRtl,Language,Scayt,Flash,Smiley,Iframe,Styles'
