services:
    _defaults:
        autowire: true
        autoconfigure: true

    HitcKit\CoreBundle\Controller\:
        resource: '../../Controller/*'
        tags: [ 'controller.service_arguments' ]
