services:
    _defaults:
        autowire: true
        autoconfigure: true

    HitcKit\CoreBundle\Controller\:
        resource: '../../Controller/*'
        tags: [ 'controller.service_arguments' ]

    HitcKit\CoreBundle\Services\:
        resource: '../../Services/*'

    HitcKit\CoreBundle\Repository\:
        resource: '../../Repository/*'
        tags: [ 'doctrine.repository_service' ]

    HitcKit\CoreBundle\Services\NodeTypeManager:
        arguments:
            - !tagged_iterator { tag: hitckit_core.node_type, index_by: key, default_index_method: getName }

    HitcKit\CoreBundle\Provider\CoreMenuProvider:
        arguments:
            - '@knp_menu.factory'
        tags:
            - { name: knp_menu.provider }

    hitc_kit_core.admin.node:
        class: HitcKit\CoreBundle\Admin\NodeAdmin
        arguments: [~, HitcKit\CoreBundle\Entity\Node, HitcKit\CoreBundle\Controller\NodeAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: base, label: tree }
        calls:
            - [ addChild, [ '@hitc_kit_core.admin.block', 'owners' ] ]
            - [ setSubClasses, [ { BlockText: HitcKit\CoreBundle\Entity\BlockText } ] ]

    hitc_kit_core.admin.block:
        class: HitcKit\CoreBundle\Admin\BlockAdmin
        arguments: [~, HitcKit\CoreBundle\Entity\Block, HitcKit\CoreBundle\Controller\BlockAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: base, label: block }
        calls:
            - [ addChild, [ '@hitc_kit_core.admin.block_text', 'parent' ] ]

    hitc_kit_core.admin.block_text:
        class: HitcKit\CoreBundle\Admin\BlockTextAdmin
        arguments: [~, HitcKit\CoreBundle\Entity\BlockText, HitcKit\CoreBundle\Controller\BlockTextAdminController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: base, label: block_text }
